project_id = "fyklcplybyfrfryopzvx"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 17

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"

[edge_runtime]
enabled = true
policy = "per_worker"
